# @package _global_
# conf/config.yaml

# Hydra의 기본 설정을 정의하는 파일입니다.
# 다른 설정 파일들을 포함하고 기본값을 설정합니다.
defaults:
  - core: base
  - paths: base
  - params: base
  - _self_

# hydra 작업 디렉토리 설정을 비활성화합니다.
# 이렇게 하면 스크립트가 실행되는 위치에 outputs 디렉토리가 생성되지 않습니다.
hydra:
  run:
    dir: .
  output_subdir: null
