# =============================================================================
# DEFAULT CONFIGURATION GROUPS
# These specify the base configurations for data, model, pipeline, prompts, and experiments.
# Hydra will merge these from conf/ subdirectories.
# =============================================================================
defaults:
- data: science_qa_bilingual
- model: default
- pipeline: default
- prompts: default
- optional experiment: null  # Optional experiment overrides; set to null if not used
- _self_

# =============================================================================
# WEIGHTS & BIASES (WANDB) INTEGRATION
# Configuration for experiment tracking and logging.
# =============================================================================
wandb:
  entity: ${env:WANDB_ENTITY}  # Your WandB entity/username from environment
  log_config_path: true  # Log the full config path for reproducibility
  project: scientific-qa-rag  # Project name for tracking runs
  run_name:
    evaluate: eval  # Run name prefix for evaluation tasks
    validate: val  # Run name prefix for validation tasks

# =============================================================================
# ANALYSIS SETTINGS
# Controls parallel processing for analysis operations.
# =============================================================================
analysis:
  enable_parallel: true  # Enable parallel execution for analysis tasks
  max_workers: null  # Number of workers; null uses default (e.g., CPU count)

# =============================================================================
# VALIDATION SET CREATION
# Parameters for generating a validation dataset.
# =============================================================================
create_validation_set:
  sample_size: 50  # Number of samples to include in the validation set

# =============================================================================
# DEBUG SETTINGS
# Global debug flags and limits for development/testing.
# =============================================================================
debug: false  # Enable debug mode (affects logging and limits)
debug_limit: 3  # Limit number of items processed in debug mode

# =============================================================================
# ELASTICSEARCH SETTINGS
# Connection details for the Elasticsearch service.
# =============================================================================
es_host: ${env:ES_HOST, "http://localhost:9200"}  # ES host URL; defaults to localhost

# =============================================================================
# EVALUATION SETTINGS
# Parameters for evaluation pipelines.
# =============================================================================
evaluate:
  max_workers: null  # Workers for evaluation; null uses default
  topk: 3  # Number of top results to evaluate (e.g., top-3 retrieval)

# =============================================================================
# INDEXING SETTINGS
# Global index name and processing limits.
# =============================================================================
index_name: ${env:INDEX_NAME, "documents_en_with_embeddings"}  # ES index name; override via env
limit: null  # Global limit on items processed; null means no limit

# =============================================================================
# REDIS SETTINGS
# Connection URL for Redis caching.
# =============================================================================
redis_url: ${env:REDIS_URL, "redis://localhost:6379/0"}  # Redis URL; defaults to localhost

# =============================================================================
# REINDEXING SETTINGS
# Parameters for reindexing operations.
# =============================================================================
reindex:
  batch_size: 500  # Batch size for reindexing documents
