ALPHA: 0.0
BM25_K: 200
EMBEDDING_MODEL: snunlp/KR-SBERT-V40K-klueNLI-augSTS
ES_HOST: http://localhost:9200
GENERATOR_MODEL_NAME: gpt-3.5-turbo
GENERATOR_SYSTEM_MESSAGE: ''
GENERATOR_SYSTEM_MESSAGE_FILE: prompts/persona_qa.txt
GENERATOR_TYPE: openai
INDEX_ALIAS: documents
INDEX_NAME: documents_bilingual_with_embeddings_new
INDEX_NAME_BILINGUAL: documents_bilingual_with_embeddings
INDEX_NAME_EN: documents_en_with_embeddings
INDEX_NAME_KO: documents_ko_with_embeddings
INDEX_NAME_PREFIX: documents_v
KEEP_OLD_INDEX_DAYS: 3
PROFILE_REPORT_DIR: outputs/reports/data_profile/latest
PROMPT_TEMPLATE_PATH: prompts/scientific_qa_v1.jinja2
REDIS_URL: redis://localhost:6379/0
REINDEX_BATCH_SIZE: 500
RERANK_K: 10
USE_DUPLICATE_FILTERING: true
USE_NEAR_DUP_PENALTY: false
USE_SRC_BOOSTS: true
USE_STOPWORD_FILTERING: false
USE_WANDB: false
WANDB_PROJECT: ir-rag
profiling_insights:
  cache_ttl_seconds: 300
  enabled: true
  memory_batch_fallback: 16
  query_expansion_terms: 3
  use_domain_routing: true
  use_dynamic_chunking: true
  use_memory_optimization: true
  use_query_expansion: true
query_enhancement:
  default_technique: rewriting
  enabled: true
  max_tokens: 500
  openai_model: gpt-3.5-turbo
  techniques:
    decomposition:
      enabled: true
      priority: 3
    hyde:
      enabled: true
      priority: 4
    rewriting:
      enabled: true
      priority: 1
    step_back:
      enabled: true
      priority: 2
    translation:
      enabled: true
      priority: 5
  temperature: 0.3
translation:
  batch_size: 100
  cache_enabled: true
  cache_ttl_days: 30
  enabled: false
  source_lang: ko
  target_lang: en
  techniques:
    decomposition:
      enabled: true
      priority: 3
    hyde:
      enabled: true
      priority: 4
    rewriting:
      enabled: true
      priority: 1
    step_back:
      enabled: true
      priority: 2
    translation:
      enabled: true
      priority: 5
  temperature: 0.3
  translation:
    bilingual_search: true
    fallback_on_error: true
  use_uv: true
