# =================================================================
# CORE SYSTEM SETTINGS
# =================================================================

# Retrieval Configuration
ALPHA: 0.4  # Balance between BM25 (0.0) and dense retrieval (1.0)
BM25_K: 200  # Number of documents to retrieve with BM25
RERANK_K: 10  # Number of documents to rerank with dense retrieval

# Embedding Configuration
EMBEDDING_MODEL: snunlp/KR-SBERT-V40K-klueNLI-augSTS
EMBEDDING_DIMENSION: 768

# Index Configuration
INDEX_NAME: documents_ko_with_embeddings_new
INDEX_ALIAS: documents
INDEX_NAME_PREFIX: documents_v
KEEP_OLD_INDEX_DAYS: 3

# Elasticsearch Configuration
ES_HOST: http://localhost:9200

# Redis Configuration
REDIS_URL: redis://localhost:6379/0

# =================================================================
# GENERATION SETTINGS
# =================================================================

# Generator Configuration
GENERATOR_TYPE: openai
GENERATOR_MODEL_NAME: gpt-3.5-turbo
GENERATOR_SYSTEM_MESSAGE_FILE: prompts/persona_qa.txt
GENERATOR_SYSTEM_MESSAGE: ''

# =================================================================
# QUERY ENHANCEMENT SETTINGS
# =================================================================

query_enhancement:
  enabled: true
  default_technique: rewriting
  max_tokens: 500
  temperature: 0.3
  openai_model: gpt-3.5-turbo

  techniques:
    rewriting:
      enabled: true
      priority: 1
    step_back:
      enabled: true
      priority: 2
    decomposition:
      enabled: true
      priority: 3
    hyde:
      enabled: true
      priority: 4
    translation:
      enabled: true
      priority: 5

# =================================================================
# TRANSLATION SETTINGS
# =================================================================

translation:
  enabled: true
  source_lang: ko
  target_lang: en
  batch_size: 100
  cache_enabled: true
  cache_ttl_days: 30
  temperature: 0.3
  use_uv: true

  # Bilingual search settings
  bilingual_search:
    enabled: true
    fallback_on_error: true

# =================================================================
# PROFILING AND OPTIMIZATION
# =================================================================

profiling_insights:
  enabled: false
  cache_ttl_seconds: 300
  memory_batch_fallback: 16
  query_expansion_terms: 3
  use_domain_routing: true
  use_dynamic_chunking: true
  use_memory_optimization: true
  use_query_expansion: true

# =================================================================
# DATA PROCESSING
# =================================================================

REINDEX_BATCH_SIZE: 500
USE_DUPLICATE_FILTERING: true
USE_NEAR_DUP_PENALTY: false
USE_SRC_BOOSTS: true
USE_STOPWORD_FILTERING: false

# =================================================================
# MONITORING AND LOGGING
# =================================================================

USE_WANDB: false
WANDB_PROJECT: ir-rag

# =================================================================
# PROMPT TEMPLATES
# =================================================================

PROMPT_TEMPLATE_PATH: prompts/scientific_qa_v1.jinja2
PROFILE_REPORT_DIR: outputs/reports/data_profile/latest
