# conf/params/base.yaml

# 모델의 하이퍼파라미터 및 실험 변수를 정의합니다.
# 이 값들은 커맨드 라인에서 쉽게 변경하여 실험할 수 있습니다.
retrieval:
  # BM25 검색에서 초기에 가져올 문서 수
  bm25_k: 200
  # 최종적으로 리랭킹하여 반환할 문서 수
  rerank_k: 10
  # 하이브리드 검색에서 BM25 점수와 코사인 유사도 점수를 결합하는 가중치
  # 0.0 = 코사인 점수만 사용, 1.0 = BM25 점수만 사용
  alpha: 0.0
  # 최대 샘플 수 (테스트용, 0이면 전체 사용)
  max_samples: 0

# 대회 제출 파일에 포함될 top-k 문서 수
submission:
  topk: 3
  # 최대 샘플 수 (테스트용, 0이면 전체 사용)
  max_samples: 0
